version: "3"
services:
  mysql1:
    image: mysql
    expose: 
      - 3306
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: vanpanda
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

  app:
    build: .
    ports:
      - 8080:8080
    links:
      - mysql1
    depends_on:
      - mysql1
